# Site settings
title: Open Access Clinic
description: "A guide to make your science 100% open access"
url: "https://openaccessclinic.github.io"

# Secondary Parameters
baseurl: ""
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"
logo: "img/logos/OAclinic.png"

# Tertiary Parameters
#github_username:
#project_repository:
#twitter_username: KMMoerman

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# # Jekyll Settings
#
# defaults:
#   -
#     scope:
#       path: "projects"
#       type: "pages"
#     values:
#       layout: "project"
#       header-img: "img/home-bg.jpg"
